name-template: v$RESOLVED_VERSION 🌈
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🚀 Features
    labels:
      - feat
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: 🧰 Maintenance
    labels:
      - build
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
template: |
  ## Changes

  $CHANGES
