name-template: v$RESOLVED_VERSION 🌈
tag-template: v$RESOLVED_VERSION
categories:
  - title: 🚀 Features
    labels:
      - feat
  - title: 💮 Improvements
    labels:
      - style
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: 🧰 Maintenance
    labels:
      - build
      - refactor
template: |
  ## Changes

  $CHANGES
