name: Release

on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed

jobs:
  release:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Publish
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
